trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DB_SERVER: '<dealmatepoc123>'
  DB_NAME: '<postgres>'
  DB_USER: '<dealmatepoc>'
  DB_PASSWORD: $(DB_PASSWORD) # Use Azure DevOps Pipeline secrets

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install flywaydb
  displayName: 'Install Flyway'

- script: |
    flyway -url=jdbc:postgresql://$(DB_SERVER).postgres.database.azure.com:5432/$(DB_NAME) \
           -user=$(DB_USER) \
           -password=$(DB_PASSWORD) \
           migrate
  displayName: 'Run Flyway Migrations'
