CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE TABLE "Dealer" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Address" text NOT NULL,
        CONSTRAINT "PK_Dealer" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE TABLE "Permission" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        CONSTRAINT "PK_Permission" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE TABLE "Role" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "RoleType" integer NOT NULL,
        CONSTRAINT "PK_Role" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE TABLE "Branch" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "DealerId" integer NOT NULL,
        CONSTRAINT "PK_Branch" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Branch_Dealer_DealerId" FOREIGN KEY ("DealerId") REFERENCES "Dealer" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE TABLE "RolePermission" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" integer NOT NULL,
        "PermissionId" integer NOT NULL,
        CONSTRAINT "PK_RolePermission" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RolePermission_Permission_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permission" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RolePermission_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE TABLE "Employee" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "BranchId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        "Email" text NOT NULL,
        "Password" text NOT NULL,
        CONSTRAINT "PK_Employee" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Employee_Branch_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branch" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Employee_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE INDEX "IX_Branch_DealerId" ON "Branch" ("DealerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE INDEX "IX_Employee_BranchId" ON "Employee" ("BranchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE INDEX "IX_Employee_RoleId" ON "Employee" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE INDEX "IX_RolePermission_PermissionId" ON "RolePermission" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    CREATE INDEX "IX_RolePermission_RoleId" ON "RolePermission" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240808101810_init') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240808101810_init', '7.0.0');
    END IF;
END $EF$;
COMMIT;

